title: Dashboard – Mapping the Data
author: harryhow
only_build_toc_files: true

execute:
  execute_notebooks: "off"   # build fast; users can run live via Thebe/Binder

html:
  use_repository_button: true
  use_edit_page_button: false
  use_issues_button: true

repository:
  url: https://github.com/harryhow/dashboard-data-rainbow
  branch: main
  path_to_book: docs

launch_buttons:
  binderhub_url: https://mybinder.org
  thebe: true

thebe:
  use_thebe_lab: true

sphinx:
  config:
    html_last_updated_fmt: "%Y-%m-%d"