name: Build & Deploy Jupyter Book to Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Jupyter Book
        run: |
          python -m pip install --upgrade pip
          pip install jupyter-book myst-nb
      - name: Build the book
        working-directory: demo
        run: jupyter-book build .
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: demo/_build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
